### ISSUE TITLE
Suggestion : A detailed cheat sheet based on React Hooks

### ISSUE THREAD

**Issue by Shubhada510** [Jahenr/CheatSheets#105]
hey! @Jahenr I saw that the cheatsheet for React Hooks is not present, I would like to add it here under hacktoberfest, please assign the issue with me and tag it as hacktoberfest if you accept the proposal. 
I think adding a detailed cheat sheet with all the essential information will help a lot of people. 
Thanks, 
Shubhada

**Comment by azulverdosa** [comment]
Hi @Shubhada510 and @Jahenr! 
I'd love to help with this if it gets off the ground!

**Comment by Shubhada510** [comment]
Hi @azulverdosa , you can go ahead with this issue.
