### ISSUE TITLE
Suggestion: Python Django Cheat Sheet

### ISSUE THREAD

**Issue by mughalmuneeb786** [Jahenr/CheatSheets#112]
There is no cheat sheet for python Django that I would like to contribute to Hacktoberfest .

**Comment by Shreyas-SAS** [comment]
Hey @mughalmuneeb786 Django Cheatsheet is already proposed earlier. I think you should not start working on it.

**Comment by mughalmuneeb786** [comment]
Ok thanks for replying

**Comment by Shreyas-SAS** [comment]
Yeah no worries. Its good if I could save your time from being wasted. I think you can easily pick some other issue. There is a lot missing here. Cheers.
