### ISSUE TITLE
Markdown CheatSheet

### ISSUE THREAD

**Issue by Candida18** [Jahenr/CheatSheets#127]
GitHub Markdown Cheatsheet with examples covering all snippets

I've already added a PR for the same 5 days back
#92

**Comment by Nashtronaut** [comment]
Hey! I could make this, can I be assigned?

**Comment by bhaskar08** [comment]
Hey Guys, I am already making the cheatsheet for markdown with referance to a previous issue and will push it in 1 hr. Please don't work on it. If there is something missing there, Please feel free to add it as a separate PR.
