### ISSUE TITLE
I want to add a JavaScript Cheatsheet

### ISSUE THREAD

**Issue by saran1522** [Jahenr/CheatSheets#192]
I want to add 2 JavaScript Cheatsheets which are in pdf form. These cheatsheets are neither created by me nor I am taking credit for them. I just want to contribute them as they can be helpful for Other Learners. THANKS!!

**Comment by saran1522** [comment]
Hello....please tell me can I make a PR for this?

**Comment by ankit060801** [comment]
hello sir,please assign me this task
