### ISSUE TITLE
Edit required: rename SQL_CheetSheet to Mariadb_CheetSheet

### ISSUE THREAD

**Issue by vai14-gaur** [Jahenr/CheatSheets#242]
The cheetsheet named with SQL_CheetSheet in the master repo has commands of Mariadb. I have  sent a pull request regarding this and updated some commands related to Mariadb like creating table, inserting new field to a table, drop column, drop rows while applying specific condition & modify existing table field. 

@JamesD17011 please review it.

**Comment by vai14-gaur** [comment]
I have sent the PR for both this edits.
#235

**Comment by JamesD17011** [comment]
Is my assistance still needed?

**Comment by vai14-gaur** [comment]
Not exactly, but I'm a beginner to contribution to open source and cannot see the updates in master repo, following that the PR is closed is that an issue?
