### ISSUE TITLE
Issue #1 To create a React.js Cheat-Sheet

### ISSUE THREAD

**Issue by ayushirastogi689** [Jahenr/CheatSheets#31]
As CheetSheet is a repo which is the central place for the most common commands used for a Project/ day to day work on System. I would like to create a Cheat Sheat for most commanly used React.js commands.

**Comment by Jahenr** [comment]
Hi ayushirastogi689

Please create and structure a md file simmilar to the python one, you could call it something like React.js_CheatSheet.md.

If you have anymore questions just let me know.

Thanks
Regards
J

**Comment by singhrishabh93** [comment]
#116 Created a React.JS Cheat Sheet for beginners
 I have created a pull request for this issue, @Jahenr kindly check the same.

**Comment by ayushirastogi689** [comment]
@Jahenr  Please assign the issue to me as I have asked for the React CheetSheet and I was waiting for you to assign it to me. Without assigning a task no PRs can be merged.
