### ISSUE TITLE
Create a powershell CheatSheet

### ISSUE THREAD

**Issue by Jahenr** [Jahenr/CheatSheets#33]
If there are any powershell kings or queens out there it would be nice to have a powershell CheatSheet with a few commands etc, It has been on the back burner for a while now.
Thank you

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man I saw your repo, I would like to contribute. Can you please assign this to me. Thank you!

**Comment by Jahenr** [comment]
Hi

Yeah sure, thanks for helping.

Regards
J

**Comment by ABHIGYAN-MOHANTA** [comment]
Sure man, Thanks

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, I have made the pr. Please don't forget to add the hacktoberfest-accepted label. And happy coding!

**Comment by Jahenr** [comment]
Hi

Thank you, I will have a look and get it merged.

Thanks again and you too.
Regards
J
