### ISSUE TITLE
Suggestion: CSS Cheat sheet

### ISSUE THREAD

**Issue by Shreyas-SAS** [Jahenr/CheatSheets#46]
hey! @Jahenr I saw that the cheatsheet for CSS is not present either, I would like to add it here under hactoberfest, please assign the issue with me and tag it as hactoberfest if you accept the proposal. thanks.

**Comment by mughalmuneeb786** [comment]
Can i Also contribute some cheat sheets and contribute to hacktoberfest.

**Comment by Shreyas-SAS** [comment]
> Can i Also contribute some cheat sheets and contribute to hacktoberfest.

Really sorry. I have started working on both the cheat sheets - CSS and js. Please pick some other one. If you need help i will be there for u. Thanks.
