### ISSUE TITLE
Suggestion: Javascript Cheat Sheet

### ISSUE THREAD

**Issue by Shreyas-SAS** [Jahenr/CheatSheets#47]
hey! @Jahenr I saw that the cheatsheet for Javascript is not present, I would like to add it here under hactoberfest, please assign the issue with me and tag it as hactoberfest if you accept the proposal. thanks.

I am revising Javascript at the moment so it will be easier for me to do the same as well.

**Comment by Shreyas-SAS** [comment]
I can also create more cheat sheets but it is best to keep them open for others, if no one makes them, I would like to complete them after Hactoberfest Finishes.

**Comment by Jahenr** [comment]
Hi

Yeah feel free to contribute whenever you can, even if its after Hacktober.
I appreciate any help 👍🏿

**Comment by mohitkrsuman** [comment]
Hii, @Jahenr I want to contribute Javascript cheat sheet as I am a beginner to open source contribution. can you please assign me?

**Comment by Shreyas-SAS** [comment]
@mohitkrsuman really sorry brother but I am about to finish the js nd css cheatsheet already. Please try some other one.
