### ISSUE TITLE
IntelliJ Idea cheat sheet

### ISSUE THREAD

**Issue by radharaniraj** [Jahenr/CheatSheets#49]
hey! @Jahenr I am planning to add IntelliJ Idea cheat sheet to this repo, please let me know if it is a good idea to add that in this repo? Can you please assign this issue to me in hacktoberfest ??

**Comment by AbhiiVops** [comment]
Heyy! @Jahenr  I wish to add the Intellij idea cheat sheet on this repo. I have pretty good hands on it. Can you please assign me this issue?

**Comment by Jahenr** [comment]
Hi everyone

Thank you for offering to contribute, please can both of you work on this together.
I will assign it to both of you.

Please keep the structure and format the  same as in the instructions and as the other CheatSheets I have created.

If you have any questions let me know. 

Thank you and enjoy contributing. 

Regards
J

**Comment by Jahenr** [comment]
Thank you AbhiiVops, I will check when I can 👍🏿
