### ISSUE TITLE
SpringBoot  Annotation CheatSheet

### ISSUE THREAD

**Issue by radharaniraj** [Jahenr/CheatSheets#50]
Hi Jahenr, I wanted to Create Cheat Sheet for SpringBoot Annotation Cheatsheet, can you please assign this issue to me.

**Comment by Jahenr** [comment]
Hi

Yeah sure. 

Same as before please keep the structure and format the same as in the instructions and as the other CheatSheets I have created.

If you have any questions let me know.

Thanks

Regards
J
