### ISSUE TITLE
I want to add DevOps complete Notes......

### ISSUE THREAD

**Issue by nihal-soni** [Jahenr/CheatSheets#62]
Hey, 
I'm Nihal 
I will contribute to your repository by adding DevOps complete Notes.....

I hope you would like my suggestion.........
Thanks

**Comment by Jahenr** [comment]
Hi Nihal

Thanks for offering to contribute, right this minute this repo is only used for commands and not notes. I was thinking possibly in the future to add a section for notes/quick guides.

I will let you know in the future 👍🏿 
Please feel free to have a look and see if there is anything you want to add or contribute too.
