### ISSUE TITLE
Want to add Java Fundamental Cheatsheet....    #Hacktoberfest2022

### ISSUE THREAD

**Issue by nihal-soni** [Jahenr/CheatSheets#66]
This will be very beneficial for Beginner

**Comment by Jahenr** [comment]
Hi nihal-soni

Please name it and structure it the the same as the others please, let me know if you have any questions.

👍🏿

**Comment by nihal-soni** [comment]
Thanks For assigning me 
I will Give my best....

**Comment by Jahenr** [comment]
No worries, thank you and enjoy contributing 👍🏿

**Comment by nihal-soni** [comment]
I have Added Java Fundamental CheatSheet.
Will you Please accept me pull request..
@Jahenr

**Comment by Jahenr** [comment]
Hi

It looks good but I thought you were going to structure it like the Python_CheatSheet.md?

**Comment by gandhi25samar** [comment]
Hey I want to take up this issue

**Comment by Jahenr** [comment]
Hi
This ticket is already assigned, I am awaiting the change to be submitted.
