### ISSUE TITLE
Cheatsheet for C language

### ISSUE THREAD

**Issue by Sukriti-m** [Jahenr/CheatSheets#67]
I will add the Cheatsheet for C language.
Please assign this issue to me and add the 'hacktoberfest' label to it. @Jahenr

**Comment by Jahenr** [comment]
Hi Sukriti-m

Please name it and structure it the the same as the others please, let me know if you have any questions.

👍🏿

**Comment by Sukriti-m** [comment]
Hey @Jahenr 
I apologize that I won't be able to work on this issue. You can go ahead and assign it to somebody else.
