### ISSUE TITLE
 Cheatsheet for C++ language

### ISSUE THREAD

**Issue by Sukriti-m** [Jahenr/CheatSheets#68]
I will add the Cheatsheet for C++ language.
Please assign this issue to me and add the 'hacktoberfest' label to it. @Jahenr

**Comment by Jahenr** [comment]
Hi Sukriti-m

Please name it and structure it the the same as the others please, let me know if you have any questions.

👍🏿

**Comment by Sukriti-m** [comment]
Hey @Jahenr 
I apologize that I won't be able to work on this issue. You can go ahead and assign it to somebody else.

**Comment by Jasmine-maryj** [comment]
Hey @Jahenr , I would like to add cheat sheet for c++ programming language.
Please assign it to me.

**Comment by Jasmine-maryj** [comment]
I have added C++ language cheatsheet, please review it.

**Comment by gandhi25samar** [comment]
Hey I want to take up this issue

**Comment by Jasmine-maryj** [comment]
#86
